use std::collections::HashMap;
use std::fs::File;
use std::io::Write;

use dotenvy::dotenv;

fn main() {
    println!("cargo:rerun-if-changed=.env");
    let mut f = File::create("./src/env.rs").unwrap();
    dotenv().ok();

    let mut variables = HashMap::new();
    variables.insert("APP_API_URL", "http://localhost:8000");

    f.write_all(b"// This file is automatically generated by build.rs\n")
        .unwrap();
    for (key, value) in variables {
        let value = std::env::var(key).unwrap_or(value.to_string());
        let line = format!(
            "\n/// * generated field *\npub const {}: &str = \"{}\";\n",
            key,
            value.replace('\"', "\\\"")
        );
        f.write_all(line.as_bytes()).unwrap();
    }
}
