use dotenv::dotenv;
use std::env;
use std::fs::File;
use std::io::Write;

fn main() {
    println!("cargo:rerun-if-changed=.env");
    let mut f = File::create("./src/env.rs").unwrap();

    // use the dotenv crate to get the .env values
    dotenv().ok();
    f.write_all(b"// This file is automatically generated by build.rs\n")
        .unwrap();
    for (key, value) in env::vars() {
        if key.starts_with("APP_") {
            let line = format!(
                "\n/// * generated field *\npub const {}: &str = \"{}\";\n",
                key,
                value.replace('\"', "\\\"")
            );
            f.write_all(line.as_bytes()).unwrap();
        }
    }
}
