[package]
name = "domain"
version = "0.0.1"
rust-version = "1.75"
edition = "2021"
authors = [ "Paweł Walus <pawel.walus@protonmail.com>" ]
description = "rusty_ops - domain module"

[lib]
name = "domain"
path = "src/lib.rs"

[dependencies]
async-graphql = "7.0"
mongodb = "2.8"
serde = { version = "1.0.197", features = ["derive"] }
