name: Daily Job

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  status:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: scripts/daily.sh
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Daily update
