name: default build

on:
  push:
    branches: ['**']

env:
  APP_API_URL: http://dummy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: true
      - name: build
        run: cargo build --release --all-features

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: true
      - name: lint
        run: |
          rustup component add clippy
          cargo clippy --all-targets --all-features -- -D warnings

  quality:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: true
      - name: tests
        run: |
          cargo check
          cargo test --all-features --no-fail-fast
